ingredients=[{"name":"Abecean Longfin","cost":44,"code":"00106e1b","where":"Collected by catching Abacean Longfin fish.","value":15,"weight":0.5,"merchants":"Common","effects":["Weakness to Frost","Fortify Sneak","Weakness to Poison","Fortify Restoration"]},
{"name":"Bear Claws","cost":65,"code":"0006bc02","where":"Collected from various types of dead Bears.","value":2,"weight":0.1,"merchants":"None (Uncommon)","effects":["Restore Stamina","Fortify Health","Fortify One-handed","Damage Magicka Regen"]},
{"name":"Bee","cost":37,"code":"000a9195","where":"Collected from beehives and by catching Bees.","value":3,"weight":0.1,"merchants":"Common","effects":["Restore Stamina","Ravage Stamina","Regenerate Stamina","Weakness to Shock"]},
{"name":"Beehive Husk","cost":42,"code":"000a9191","where":"Collected from beehives.","value":5,"weight":1,"merchants":"None (Common)","effects":["Resist Poison (0.5×)","Fortify Light Armor","Fortify Sneak","Fortify Destruction"]},
{"name":"Bleeding Crown","cost":36,"code":"0004da20","where":"Harvested from Bleeding Crown, a mushroom found in various caves.","value":10,"weight":0.3,"merchants":"Uncommon","effects":["Weakness to Fire","Fortify Block","Weakness to Poison","Resist Magic"]},
{"name":"Blisterwort","cost":33,"code":"0004da25","where":"Harvested from Blisterwort mushrooms found in various caves.","value":12,"weight":0.2,"merchants":"Uncommon","effects":["Damage Stamina","Frenzy","Restore Health (0.6×)","Fortify Smithing"]},
{"name":"Blue Butterfly Wing","cost":54,"code":"000727de","where":"Collected by catching Blue Butterflies. Often found during daylight hours near flowering plants.","value":2,"weight":0.1,"merchants":"Uncommon","effects":["Damage Stamina","Fortify Conjuration","Damage Magicka Regen","Fortify Enchanting"]},
{"name":"Blue Dartwing","cost":46,"code":"000e4f0c","where":"Collected by catching Dragonflies found near rivers and streams below the snow line.","value":1,"weight":0.1,"merchants":"None (Uncommon)","effects":["Resist Shock","Fortify Pickpocket","Restore Health","Fear"]},
{"name":"Blue Mountain Flower","cost":59,"code":"00077e1c","where":"Harvested from the blue variety of Mountain Flower, found throughout Skyrim.","value":2,"weight":0.1,"merchants":"Common","effects":["Restore Health","Fortify Conjuration","Fortify Health","Damage Magicka Regen"]},
{"name":"Bone Meal","cost":31,"code":"00034cdd","where":"Collected from undead such as skeletons, and Draugr.","value":5,"weight":0.5,"merchants":"Common","effects":["Damage Stamina","Resist Fire","Fortify Conjuration","Ravage Stamina"]},
{"name":"Briar Heart","cost":58,"code":"0003ad61","where":"Collected from Forsworn Briarhearts.","value":20,"weight":0.5,"merchants":"Rare","effects":["Restore Magicka","Fortify Block (0.5×)","Paralysis","Fortify Magicka"]},
{"name":"Butterfly Wing","cost":16,"code":"000727e0","where":"Collected from catching Monarch Butterflies. Often found during daylight hours near flowering plants.","value":3,"weight":0.1,"merchants":"Uncommon","effects":["Restore Health","Fortify Barter","Lingering Damage Stamina","Damage Magicka"]},
{"name":"Canis Root","cost":77,"code":"0006abcb","where":"Harvested from Canis Root, found in The Rift and Hjaalmarch.","value":5,"weight":0.1,"merchants":"Uncommon","effects":["Damage Stamina","Fortify One-handed","Fortify Marksman","Paralysis"]},
{"name":"Charred Skeever Hide","cost":22,"code":"00052695","where":"Food, collected from dead Skeevers found on roasting spits.","value":1,"weight":0.5,"merchants":"Uncommon","effects":["Restore Stamina","Cure Disease (0.4dur)","Resist Poison","Restore Health"]},
{"name":"Chaurus Eggs","cost":59,"code":"0003ad56","where":"Collected from Chaurus Egg Sacs, found in Falmer caves.","value":10,"weight":0.2,"merchants":"Uncommon","effects":["Weakness to Poison","Fortify Stamina","Damage Magicka","Invisibility"]},
{"name":"Chicken's Egg","cost":57,"code":"00023d77","where":"Food, harvested from Chicken nests in various farms.","value":2,"weight":0.5,"merchants":"Common","effects":["Resist Magic","Damage Magicka Regen","Waterbreathing","Lingering Damage Stamina"]},
{"name":"Creep Cluster","cost":61,"code":"000b2183","where":"Harvested from Creep Cluster, found in the volcanic tundra of Eastmarch.","value":1,"weight":0.2,"merchants":"Uncommon","effects":["Restore Magicka","Damage Stamina Regen","Fortify Carry Weight","Weakness to Magic"]},
{"name":"Crimson Nirnroot","cost":64,"code":"000b701a","where":"Harvested from Crimson Nirnroot, found in Blackreach.","value":10,"weight":0.2,"merchants":"None","effects":["Damage Health (3×)","Damage Stamina (3×)","Invisibility","Resist Magic"]},
{"name":"Cyrodilic Spadetail","cost":38,"code":"00106e19","where":"Collected by catching Cyrodilic Spadetail fish.","value":15,"weight":0.25,"merchants":"Common","effects":["Damage Stamina","Fortify Restoration","Fear","Ravage Health"]},
{"name":"Daedra Heart","cost":47,"code":"0003ad5b","where":"Collected from dead Dremora.","value":250,"weight":0.5,"merchants":"Rare","effects":["Restore Health","Damage Stamina Regen","Damage Magicka","Fear"]},
{"name":"Deathbell","cost":48,"code":"000516c8","where":"Harvested from Deathbell, found in Hjaalmarch.","value":4,"weight":0.1,"merchants":"Rare","effects":["Damage Health (1.5×)","Ravage Stamina (2.0dur)","Slow","Weakness to Poison"]},
{"name":"Dragon's Tongue","cost":36,"code":"000889a2","where":"Harvested from Dragon's Tongue, found in the volcanic tundra of Eastmarch.","value":5,"weight":0.1,"merchants":"Common","effects":["Resist Fire","Fortify Barter","Fortify Illusion","Fortify Two-handed"]},
{"name":"Dwarven Oil","cost":47,"code":"000f11c0","where":"Collected from destroyed Dwarven Automatons, found in Dwarven Ruins.","value":15,"weight":0.25,"merchants":"Uncommon","effects":["Weakness to Magic","Fortify Illusion","Regenerate Magicka","Restore Magicka"]},
{"name":"Ectoplasm","cost":28,"code":"0003ad63","where":"Collected from undead Ghosts.","value":25,"weight":0.1,"merchants":"Uncommon","effects":["Restore Magicka","Fortify Destruction (0.8×)","Fortify Magicka","Damage Health"]},
{"name":"Elves Ear","cost":27,"code":"00034d31","where":"Harvested from Dried Elves Ear bunches found in homes and camps.","value":10,"weight":0.1,"merchants":"Common","effects":["Restore Magicka","Fortify Marksman","Weakness to Frost","Resist Fire"]},
{"name":"Eye of Sabre Cat","cost":12,"code":"0006bc07","where":"Collected from dead Sabre Cats.","value":2,"weight":0.1,"merchants":"None (Uncommon)","effects":["Restore Stamina","Ravage Health","Damage Magicka","Restore Health"]},
{"name":"Falmer Ear","cost":34,"code":"0003ad5d","where":"Collected from dead Falmer.","value":10,"weight":0.2,"merchants":"Uncommon","effects":["Damage Health","Frenzy","Resist Poison","Fortify Lockpicking"]},
{"name":"Fire Salts","cost":44,"code":"0003ad5e","where":"Collected from dead Flame Atronachs, a type of daedra.","value":50,"weight":0.25,"merchants":"Rare","effects":["Weakness to Frost","Resist Fire","Restore Magicka","Regenerate Magicka"]},
{"name":"Fly Amanita","cost":67,"code":"0004da00","where":"Harvested from Fly Amanita mushrooms, found in various caves.","value":2,"weight":0.1,"merchants":"Uncommon","effects":["Resist Fire","Fortify Two-handed","Frenzy","Regenerate Stamina"]},
{"name":"Frost Mirriam","cost":52,"code":"00034d32","where":"Harvested from Dried Frost Mirriam bunches found in homes and camps.","value":1,"weight":0.1,"merchants":"Uncommon","effects":["Resist Frost","Fortify Sneak","Ravage Magicka","Damage Stamina Regen"]},
{"name":"Frost Salts","cost":31,"code":"0003ad5f","where":"Collected from dead Frost Atronachs, a type of daedra.","value":100,"weight":0.25,"merchants":"Rare","effects":["Weakness to Fire","Resist Frost","Restore Magicka","Fortify Conjuration"]},
{"name":"Garlic","cost":73,"code":"00034d22","where":"Food. Can also be harvested from Garlic Braids.","value":1,"weight":0.25,"merchants":"Common","effects":["Resist Poison","Fortify Stamina","Regenerate Magicka","Regenerate Health"]},
{"name":"Giant Lichen","cost":17,"code":"0007e8c1","where":"Harvested from Giant Lichen, found in Hjaalmarch.","value":5,"weight":0.25,"merchants":"Uncommon","effects":["Weakness to Shock","Ravage Health","Weakness to Poison","Restore Magicka"]},
{"name":"Giant's Toe","cost":124,"code":"0003ad64","where":"Collected from dead Giants, which can be found in Giant Camps.","value":20,"weight":1,"merchants":"Rare","effects":["Damage Stamina","Fortify Health (5.0dur)","Fortify Carry Weight","Damage Stamina Regen"]},
{"name":"Glow Dust","cost":76,"code":"0003ad73","where":"Collected from dead Wisps and Wispmothers.","value":20,"weight":0.5,"merchants":"Uncommon","effects":["Damage Magicka","Damage Magicka Regen","Fortify Destruction","Resist Shock"]},
{"name":"Glowing Mushroom","cost":55,"code":"0007ee01","where":"Harvested from Glowing Mushrooms, found in various caves.","value":5,"weight":0.2,"merchants":"None","effects":["Resist Shock","Fortify Destruction","Fortify Smithing","Fortify Health"]},
{"name":"Grass Pod","cost":27,"code":"00083e64","where":"Harvested from Spiky Grass, found in northern regions of Skyrim.","value":1,"weight":0.1,"merchants":"Uncommon","effects":["Resist Poison","Ravage Magicka","Fortify Alteration","Restore Magicka"]},
{"name":"Hagraven Claw","cost":25,"code":"0006b689","where":"Collected from dead Hagravens.","value":20,"weight":0.25,"merchants":"Rare","effects":["Resist Magic","Lingering Damage Magicka","Fortify Enchanting","Fortify Barter"]},
{"name":"Hagraven Feathers","cost":39,"code":"0003ad66","where":"Collected from dead Hagravens. Can also be found scattered around their sleeping areas.","value":20,"weight":0.1,"merchants":"Rare","effects":["Damage Magicka","Fortify Conjuration","Frenzy","Weakness to Shock"]},
{"name":"Hanging Moss","cost":70,"code":"00057f91","where":"Harvested from Hanging Moss.","value":1,"weight":0.25,"merchants":"Uncommon","effects":["Damage Magicka","Fortify Health","Damage Magicka Regen","Fortify One-handed"]},
{"name":"Hawk Beak","cost":56,"code":"000e7ebc","where":"Collected from dead Hawks.","value":15,"weight":0.25,"merchants":"Uncommon","effects":["Restore Stamina","Resist Frost","Fortify Carry Weight","Resist Shock"]},
{"name":"Hawk Feathers","cost":40,"code":"000e7ed0","where":"Collected from dead Hawks.","value":15,"weight":0.1,"merchants":"Uncommon","effects":["Cure Disease (0.4×)","Fortify Light Armor","Fortify One-handed","Fortify Sneak"]},
{"name":"Histcarp","cost":47,"code":"00106e18","where":"Collected by catching Histcarp fish.","value":6,"weight":0.25,"merchants":"Common","effects":["Restore Stamina","Fortify Magicka","Damage Stamina Regen","Waterbreathing"]},
{"name":"Honeycomb","cost":20,"code":"000b08c5","where":"Food. Collected from beehives.","value":5,"weight":1,"merchants":"None (Common)","effects":["Restore Stamina","Fortify Block (0.5×)","Fortify Light Armor","Ravage Stamina"]},
{"name":"Human Flesh","cost":58,"code":"001016b3","where":"Cannot be harvested or collected; limited number of samples available.","value":1,"weight":0.25,"merchants":"None","effects":["Damage Health","Paralysis","Restore Magicka","Fortify Sneak"]},
{"name":"Human Heart","cost":58,"code":"000b18cd","where":"Cannot be harvested or collected; limited number of samples available.","value":0,"weight":1,"merchants":"None","effects":["Damage Health","Damage Magicka","Damage Magicka Regen","Frenzy"]},
{"name":"Ice Wraith Teeth","cost":54,"code":"0003ad6a","where":"Collected from Ice Wraiths.","value":30,"weight":0.25,"merchants":"Rare","effects":["Weakness to Frost","Fortify Heavy Armor","Invisibility","Weakness to Fire"]},
{"name":"Imp Stool","cost":52,"code":"0004da23","where":"Harvested from Imp Stool mushrooms, found in various caves.","value":0,"weight":0.3,"merchants":"Rare","effects":["Damage Health","Lingering Damage Health","Paralysis","Restore Health (0.6×)"]},
{"name":"Jazbay Grapes","cost":40,"code":"0006ac4a","where":"Harvested from Jazbay vines, found in the volcanic tundra of Eastmarch.","value":1,"weight":0.2,"merchants":"Rare","effects":["Weakness to Magic","Fortify Magicka","Regenerate Magicka","Ravage Health"]},
{"name":"Juniper Berries","cost":68,"code":"0005076e","where":"Harvested from Juniper shrubs, common in The Reach.","value":1,"weight":0.1,"merchants":"Common","effects":["Weakness to Fire","Fortify Marksman","Regenerate Health","Damage Stamina Regen"]},
{"name":"Large Antlers","cost":53,"code":"0006bc0a","where":"Collected from dead male Elk.","value":2,"weight":0.1,"merchants":"None (Uncommon)","effects":["Restore Stamina","Fortify Stamina","Slow","Damage Stamina Regen"]},
{"name":"Lavender","cost":26,"code":"00045c28","where":"Harvested from Lavender, most common in Whiterun Hold.","value":1,"weight":0.1,"merchants":"Common","effects":["Resist Magic","Fortify Stamina","Ravage Magicka","Fortify Conjuration"]},
{"name":"Luna Moth Wing","cost":74,"code":"000727df","where":"Collected by catching Luna Moths. Often found near flowers after dark.","value":5,"weight":0.1,"merchants":"Uncommon","effects":["Damage Magicka","Fortify Light Armor","Regenerate Health","Invisibility"]},
{"name":"Moon Sugar","cost":45,"code":"000d8e3e","where":"Cannot be collected or harvested. Can be purchased from the Khajiit Traders.","value":50,"weight":0.25,"merchants":"Uncommon","effects":["Weakness to Fire","Resist Frost","Restore Magicka","Regenerate Magicka"]},
{"name":"Mora Tapinella","cost":52,"code":"000ec870","where":"Harvested from Mora Tapinella mushrooms, found growing on dead trees.","value":4,"weight":0.25,"merchants":"Uncommon","effects":["Restore Magicka","Lingering Damage Health","Regenerate Stamina","Fortify Illusion"]},
{"name":"Mudcrab Chitin","cost":33,"code":"0006bc00","where":"Collected from dead Mudcrabs, found in or near bodies of water.","value":2,"weight":0.25,"merchants":"None (Common)","effects":["Restore Stamina","Cure Disease","Resist Poison","Resist Fire"]},
{"name":"Namira's Rot","cost":50,"code":"0004da24","where":"Harvested from Namira's Rot mushrooms, found in various caves.","value":0,"weight":0.25,"merchants":"Uncommon","effects":["Damage Magicka","Fortify Lockpicking","Fear","Regenerate Health"]},
{"name":"Nightshade","cost":53,"code":"0002f44c","where":"Harvested from Nightshade, found growing throughout Skyrim.","value":8,"weight":0.1,"merchants":"Rare","effects":["Damage Health","Damage Magicka Regen","Lingering Damage Stamina","Fortify Destruction (0.8×)"]},
{"name":"Nirnroot","cost":55,"code":"00059b86","where":"Harvested from Nirnroot, found near bodies of water throughout Skyrim.","value":10,"weight":0.2,"merchants":"Rare","effects":["Damage Health (10.0dur)","Damage Stamina","Invisibility","Resist Magic"]},
{"name":"Nordic Barnacle","cost":60,"code":"0007edf5","where":"Harvested from Nordic Barnacle Clusters, found in or near water.","value":5,"weight":0.2,"merchants":"Uncommon","effects":["Damage Magicka","Waterbreathing","Regenerate Health","Fortify Pickpocket"]},
{"name":"Orange Dartwing","cost":33,"code":"000bb956","where":"Collected by catching Dragonflies found near rivers and streams below the snow line.","value":1,"weight":0.1,"merchants":"None (Common)","effects":["Restore Stamina","Ravage Magicka","Fortify Pickpocket","Lingering Damage Health"]},
{"name":"Pearl","cost":34,"code":"000854fe","where":"Cannot be harvested or collected; only readily available after the Merchant perk has been unlocked.","value":2,"weight":0.1,"merchants":"None (Uncommon)","effects":["Restore Stamina","Fortify Block","Restore Magicka","Resist Shock"]},
{"name":"Pine Thrush Egg","cost":25,"code":"00023d6f","where":"Harvested from bird nests in forested regions, in particular The Rift.","value":2,"weight":0.5,"merchants":"Common","effects":["Restore Stamina","Fortify Lockpicking","Weakness to Poison","Resist Shock"]},
{"name":"Powdered Mammoth Tusk","cost":41,"code":"0006bc10","where":"Cannot be harvested or collected; only readily available after the Merchant perk has been unlocked.","value":2,"weight":0.1,"merchants":"None (Uncommon)","effects":["Restore Stamina","Fortify Sneak","Weakness to Fire","Fear"]},
{"name":"Purple Mountain Flower","cost":41,"code":"00077e1e","where":"Harvested from the purple variety of Mountain Flower.","value":2,"weight":0.1,"merchants":"Common","effects":["Restore Stamina","Fortify Sneak","Lingering Damage Magicka","Resist Frost"]},
{"name":"Red Mountain Flower","cost":14,"code":"00077e1d","where":"Harvested from the red variety of Mountain Flower.","value":2,"weight":0.1,"merchants":"Common","effects":["Restore Magicka","Ravage Magicka","Fortify Magicka","Damage Health"]},
{"name":"River Betty","cost":86,"code":"00106e1a","where":"Collected by catching River Betty fish.","value":15,"weight":0.25,"merchants":"Common","effects":["Damage Health (2.5×) (10.0dur)","Fortify Alteration","Slow","Fortify Carry Weight"]},
{"name":"Rock Warbler Egg","cost":31,"code":"0007e8c8","where":"Harvested from bird nests in rocky regions, in particular The Reach.","value":2,"weight":0.5,"merchants":"Uncommon","effects":["Restore Health","Fortify One-handed","Damage Stamina","Weakness to Magic"]},
{"name":"Sabre Cat Tooth","cost":28,"code":"0006bc04","where":"Collected from dead Sabre cats.","value":2,"weight":0.1,"merchants":"None (Uncommon)","effects":["Restore Stamina","Fortify Heavy Armor","Fortify Smithing","Weakness to Poison"]},
{"name":"Salt Pile","cost":81,"code":"00034cdf","where":"Food. Cannot be harvested or collected, but is commonly found in barrels and sacks.","value":2,"weight":0.2,"merchants":"Common","effects":["Weakness to Magic","Fortify Restoration","Slow","Regenerate Magicka"]},
{"name":"Scaly Pholiota","cost":73,"code":"0006f950","where":"Harvested from Scaly Pholiota mushrooms, found growing on dead trees.","value":4,"weight":0.25,"merchants":"Uncommon","effects":["Weakness to Magic","Fortify Illusion","Regenerate Stamina","Fortify Carry Weight"]},
{"name":"Silverside Perch","cost":37,"code":"00106e1c","where":"Collected by catching Silverside Perch fish.","value":15,"weight":0.25,"merchants":"Common","effects":["Restore Stamina","Damage Stamina Regen","Ravage Health","Resist Frost"]},
{"name":"Skeever Tail","cost":29,"code":"0003ad6f","where":"Collected from dead Skeevers.","value":3,"weight":0.2,"merchants":"Common","effects":["Damage Stamina Regen","Ravage Health","Damage Health","Fortify Light Armor"]},
{"name":"Slaughterfish Egg","cost":53,"code":"0007e8c5","where":"Collected from Slaughterfish Egg Nests, found in or near water.","value":3,"weight":0.2,"merchants":"Uncommon","effects":["Resist Poison","Fortify Pickpocket","Lingering Damage Health","Fortify Stamina"]},
{"name":"Slaughterfish Scales","cost":47,"code":"0003ad70","where":"Collected from dead Slaughterfish.","value":3,"weight":0.1,"merchants":"Uncommon","effects":["Resist Frost","Lingering Damage Health","Fortify Heavy Armor","Fortify Block"]},
{"name":"Small Antlers","cost":24,"code":"0006bc0b","where":"Collected from dead female Elk.","value":2,"weight":0.1,"merchants":"None (Common)","effects":["Weakness to Poison","Fortify Restoration","Lingering Damage Stamina","Damage Health"]},
{"name":"Small Pearl","cost":47,"code":"85500","where":"Cannot be harvested or collected; only readily available after the Merchant perk has been unlocked.","value":2,"weight":0.1,"merchants":"None (Uncommon)","effects":["Restore Stamina","Fortify One-handed","Fortify Restoration","Resist Frost"]},
{"name":"Snowberries","cost":38,"code":"0001b3bd","where":"Harvested from Snowberry bushes, found in snowy regions of Skyrim.","value":4,"weight":0.1,"merchants":"Common","effects":["Resist Fire","Fortify Enchanting","Resist Frost","Resist Shock"]},
{"name":"Spider Egg","cost":61,"code":"0009151b","where":"Collected from spider Egg Sacs and Web Sacs.","value":5,"weight":0.2,"merchants":"Uncommon","effects":["Damage Stamina","Damage Magicka Regen","Fortify Lockpicking","Fortify Marksman"]},
{"name":"Spriggan Sap","cost":55,"code":"00063b5f","where":"Cannot be harvested or collected; best source is merchants.","value":15,"weight":0.2,"merchants":"Uncommon","effects":["Damage Magicka Regen","Fortify Enchanting","Fortify Smithing","Fortify Alteration"]},
{"name":"Swamp Fungal Pod","cost":63,"code":"0007e8b7","where":"Harvested from Swamp Fungal Pod, common in the tundra marsh of Hjaalmarch.","value":5,"weight":0.25,"merchants":"Uncommon","effects":["Resist Shock","Lingering Damage Magicka","Paralysis","Restore Health"]},
{"name":"Taproot","cost":47,"code":"0003ad71","where":"Collected from dead Spriggans.","value":15,"weight":0.5,"merchants":"Uncommon","effects":["Weakness to Magic","Fortify Illusion","Regenerate Magicka","Restore Magicka"]},
{"name":"Thistle Branch","cost":23,"code":"000134aa","where":"Harvested from Thistle.","value":1,"weight":0.1,"merchants":"Common","effects":["Resist Frost","Ravage Stamina","Resist Poison (0.75×)","Fortify Heavy Armor"]},
{"name":"Torchbug Thorax","cost":29,"code":"0004da73","where":"Collected by catching Torchbugs. Found below the snowline after dark.","value":1,"weight":0.1,"merchants":"None (Common)","effects":["Restore Stamina","Lingering Damage Magicka","Weakness to Magic","Fortify Stamina"]},
{"name":"Troll Fat","cost":47,"code":"0003ad72","where":"Collected from dead Trolls.","value":15,"weight":1,"merchants":"Uncommon","effects":["Resist Poison","Fortify Two-handed","Frenzy","Damage Health"]},
{"name":"Tundra Cotton","cost":38,"code":"0003f7f8","where":"Harvested from Tundra Cotton, found in Whiterun Hold.","value":1,"weight":0.1,"merchants":"Common","effects":["Resist Magic","Fortify Magicka","Fortify Block","Fortify Barter"]},
{"name":"Vampire Dust","cost":65,"code":"0003ad76","where":"Collected from dead Vampires.","value":25,"weight":0.2,"merchants":"Rare","effects":["Invisibility","Restore Magicka","Regenerate Health","Cure Disease"]},
{"name":"Void Salts","cost":23,"code":"0003ad60","where":"Collected from dead Storm Atronachs.","value":125,"weight":0.2,"merchants":"Rare","effects":["Weakness to Shock","Resist Magic","Damage Health","Fortify Magicka"]},
{"name":"Wheat","cost":45,"code":"0004b0ba","where":"Food. Harvested from wheat bushels, found in various farms.","value":5,"weight":0.1,"merchants":"Common","effects":["Restore Health","Fortify Health","Damage Stamina Regen","Lingering Damage Magicka"]},
{"name":"White Cap","cost":17,"code":"0004da22","where":"Harvested from White Cap mushrooms, found in various caves.","value":0,"weight":0.3,"merchants":"Uncommon","effects":["Weakness to Frost","Fortify Heavy Armor","Restore Magicka","Ravage Magicka"]},
{"name":"Wisp Wrappings","cost":60,"code":"0006bc0e","where":"Collected from dead Wispmothers.","value":2,"weight":0.1,"merchants":"None (Uncommon)","effects":["Restore Stamina","Fortify Destruction","Fortify Carry Weight","Resist Magic"]},
{"name":"Berit's Ashes","groups":["Unique/Quest"],"cost":31,"code":"000705b7","where":"This ingredient is given as a quest item. Its effects are all identical to standard Bone Meal.","value":5,"weight":0.2,"merchants":"None","effects":["Damage Stamina","Resist Fire","Fortify Conjuration","Ravage Stamina"]},
{"name":"Jarrin Root","groups":["Unique/Quest"],"cost":129,"code":"0001bcbc","where":"You may only receive this ingredient once during the Dark Brotherhood quest line.","value":10,"weight":0.5,"merchants":"None","effects":["Damage Health (100×)","Damage Magicka","Damage Stamina","Damage Magicka Regen"]},
{"name":"Ancestor Moth Wings","groups":["Dawnguard"],"cost":54,"code":"xx0059ba","where":"Collected by catching Ancestor Moths.","value":2,"weight":0.1,"merchants":"None","effects":["Damage Stamina","Fortify Conjuration","Damage Magicka Regen","Fortify Enchanting"]},
{"name":"Chaurus Hunter Antennae","groups":["Dawnguard"],"cost":54,"code":"xx0183b7","where":"Collected from dead Chaurus Hunters and Chaurus Hunter Fledglings.","value":2,"weight":0.1,"merchants":"None","effects":["Damage Stamina","Fortify Conjuration","Damage Magicka Regen","Fortify Enchanting"]},
{"name":"Gleamblossom","groups":["Dawnguard"],"cost":86,"code":"xx00b097","where":"Harvested from the plant of the same name.","value":5,"weight":0.1,"merchants":"Common","effects":["Resist Magic","Fear","Regenerate Health","Paralysis"]},
{"name":"Poison Bloom","groups":["Dawnguard"],"cost":79,"code":"xx0185fb","where":"Harvested from the plant of the same name.","value":5,"weight":0.25,"merchants":"None","effects":["Damage Health (1.5×)","Slow","Fortify Carry Weight","Fear"]},
{"name":"Yellow Mountain Flower","groups":["Dawnguard"],"cost":70,"code":"xx002a78","where":"Harvested from the yellow variety of Mountain Flower.","value":2,"weight":0.1,"merchants":"None","effects":["Resist Poison","Fortify Restoration (1.25×)","Fortify Health","Damage Stamina Regen"]},
{"name":"Salmon Roe","groups":["Hearthfire"],"cost":250,"code":"xx003545","where":"Harvested from jumping Salmon.","value":5,"weight":0.2,"merchants":"None","effects":["Restore Stamina (0.4×)","Waterbreathing (12.0dur)","Fortify Magicka (12.5×) (12durdiv)","Regenerate Magicka"]},
{"name":"Hawk's Egg","groups":["Hearthfire"],"cost":57,"code":"xx00F1CC","where":"Hawk's Eggs can be harvested from hawks' nests.","value":5,"weight":0.5,"merchants":"None","effects":["Resist Magic","Damage Magicka Regen","Waterbreathing","Lingering Damage Stamina"]},
{"name":"Ash Creep Cluster","groups":["Dragonborn"],"cost":75,"code":"xx01cd74","where":"Harvested from creep cluster plants unique to Solstheim.","value":20,"weight":0.25,"merchants":"None","effects":["Damage Stamina","Invisibility","Resist Fire","Fortify Destruction"]},
{"name":"Ash Hopper Jelly","groups":["Dragonborn"],"cost":26,"code":"xx01cd71","where":"Collected from dead ash hoppers.","value":20,"weight":0.25,"merchants":"None","effects":["Restore Health","Fortify Light Armor","Resist Shock","Weakness to Frost"]},
{"name":"Ashen Grass Pod","groups":["Dragonborn"],"cost":42,"code":"xx016e26","where":"Harvested from spiky grass plants unique to Solstheim.","value":1,"weight":0.1,"merchants":"None","effects":["Resist Fire (4.0×) (3.0×div)","Weakness to Shock","Fortify Lockpicking","Fortify Sneak"]},
{"name":"Boar Tusk","groups":["Dragonborn"],"cost":172,"code":"xx01cd6f","where":"Collected from dead bristlebacks and rieklings.","value":20,"weight":0.5,"merchants":"None","effects":["Fortify Stamina (1.25×) (5.0dur)","Fortify Health (5.0dur)","Fortify Block","Frenzy"]},
{"name":"Burnt Spriggan Wood","groups":["Dragonborn"],"cost":82,"code":"xx01cd6e","where":"Collected from dead burnt spriggans.","value":20,"weight":0.5,"merchants":"None","effects":["Weakness to Fire","Fortify Alteration","Damage Magicka Regen","Slow"]},
{"name":"Emperor Parasol Moss","groups":["Dragonborn"],"cost":59,"code":"xx01ff75","where":"Harvested from emperor parasol moss plants near Tel Mithryn.","value":1,"weight":0.25,"merchants":"None","effects":["Damage Health (1.5×)","Fortify Magicka","Regenerate Health","Fortify Two-handed"]},
{"name":"Felsaad Tern Feathers","groups":["Dragonborn"],"cost":16,"code":"xx03cd8e","where":"Collected from dead Felsaad terns.","value":15,"weight":0.1,"merchants":"None","effects":["Restore Health (0.2×)","Fortify Light Armor","Cure Disease","Resist Magic"]},
{"name":"Netch Jelly","groups":["Dragonborn"],"cost":91,"code":"xx01cd72","where":"Collected from dead netch.","value":20,"weight":0.5,"merchants":"None","effects":["Paralysis","Fortify Carry Weight","Restore Stamina (2.0×)","Fear"]},
{"name":"Scathecraw","groups":["Dragonborn"],"cost":17,"code":"xx017e97","where":"Harvested from scathecraw plants.","value":1,"weight":0.1,"merchants":"None","effects":["Ravage Health","Ravage Stamina","Ravage Magicka","Lingering Damage Health"]},
{"name":"Spawn Ash","groups":["Dragonborn"],"cost":19,"code":"xx01cd6d","where":"Collected from dead ash spawn.","value":20,"weight":0.1,"merchants":"None","effects":["Ravage Stamina","Resist Fire","Fortify Enchanting","Ravage Magicka"]},
{"name":"Trama Root","groups":["Dragonborn"],"cost":77,"code":"xx017008","where":"Harvested from trama root plants.","value":1,"weight":0.2,"merchants":"None","effects":["Weakness to Shock","Fortify Carry Weight","Damage Magicka","Slow"]}

//,
//{"name":"Salt Pile","cost":81,"code":"00074a19","where":"This is a quest-specific variety of Salt Pile, associated with the quest Promises to Keep. Its effects are all identical to standard Salt Pile.","value":2,"weight":0.2,"merchants":"None","effects":["Weakness to Magic","Fortify Restoration","Slow","Regenerate Magicka"]}
];
var allEffects = {
"Cure Disease":{isPotion:true,fixedMagnitude:false,baseMagnitude:5,fixedDuration:true,baseDuration:0,description:"Cures all diseases.",baseGold:0.5}
,"Damage Health":{isPotion:false,fixedMagnitude:false,baseMagnitude:2,fixedDuration:true,baseDuration:1,description:"Causes <mag> points of poison damage.",baseGold:3}
,"Damage Magicka":{isPotion:false,fixedMagnitude:false,baseMagnitude:3,fixedDuration:true,baseDuration:0,description:"Drains the target's Magicka by <mag> points.",baseGold:2.2}
,"Damage Magicka Regen":{isPotion:false,fixedMagnitude:true,baseMagnitude:100,fixedDuration:false,baseDuration:5,description:"Decrease the target's Magicka regeneration by <mag>% for <dur> seconds.",baseGold:0.5}
,"Damage Stamina":{isPotion:false,fixedMagnitude:false,baseMagnitude:3,fixedDuration:true,baseDuration:0,description:"Drain the target's Stamina by <mag> points.",baseGold:1.8}
,"Damage Stamina Regen":{isPotion:false,fixedMagnitude:true,baseMagnitude:100,fixedDuration:false,baseDuration:5,description:"Decrease the target's Stamina regeneration by <mag>% for <dur> seconds.",baseGold:0.3}
,"Fear":{isPotion:false,fixedMagnitude:false,baseMagnitude:1,fixedDuration:true,baseDuration:30,description:"Creatures and people up to level <mag> flee from combat for <dur> seconds.",baseGold:5}
,"Fortify Alteration":{isPotion:true,fixedMagnitude:false,baseMagnitude:4,fixedDuration:true,baseDuration:60,description:"Alteration spells last <mag>% longer for <dur> seconds.",baseGold:0.2}
,"Fortify Barter":{isPotion:true,fixedMagnitude:false,baseMagnitude:1,fixedDuration:true,baseDuration:30,description:"You haggle for <mag>% better prices for <dur> seconds.",baseGold:2}
,"Fortify Block":{isPotion:true,fixedMagnitude:false,baseMagnitude:4,fixedDuration:true,baseDuration:60,description:"Blocking absorbs <mag>% more damage for <dur> seconds.",baseGold:0.5}
,"Fortify Carry Weight":{isPotion:true,fixedMagnitude:false,baseMagnitude:4,fixedDuration:true,baseDuration:300,description:"Carrying capacity increases by <mag> for <dur> seconds.",baseGold:0.15}
,"Fortify Conjuration":{isPotion:true,fixedMagnitude:false,baseMagnitude:5,fixedDuration:true,baseDuration:60,description:"Conjurations spells last <mag>% longer for <dur> seconds.",baseGold:0.25}
,"Fortify Destruction":{isPotion:true,fixedMagnitude:false,baseMagnitude:5,fixedDuration:true,baseDuration:60,description:"Destruction spells are <mag>% stronger for <dur> seconds.",baseGold:0.5}
,"Fortify Enchanting":{isPotion:true,fixedMagnitude:false,baseMagnitude:1,fixedDuration:true,baseDuration:30,description:"For <dur> seconds, items are enchanted <mag>% stronger.",baseGold:0.6}
,"Fortify Health":{isPotion:true,fixedMagnitude:false,baseMagnitude:4,fixedDuration:true,baseDuration:60,description:"Health is increased by <mag> points for <dur> seconds.",baseGold:0.35}
,"Fortify Heavy Armor":{isPotion:true,fixedMagnitude:false,baseMagnitude:2,fixedDuration:true,baseDuration:60,description:"Increase Heavy Armor skill by <mag> points for <dur> seconds.",baseGold:0.5}
,"Fortify Illusion":{isPotion:true,fixedMagnitude:false,baseMagnitude:4,fixedDuration:true,baseDuration:60,description:"Illusion spells are <mag>% stronger for <dur> seconds.",baseGold:0.4}
,"Fortify Light Armor":{isPotion:true,fixedMagnitude:false,baseMagnitude:2,fixedDuration:true,baseDuration:60,description:"Increases Light Armor skill by <mag> points for <dur> seconds.",baseGold:0.5}
,"Fortify Lockpicking":{isPotion:true,fixedMagnitude:false,baseMagnitude:2,fixedDuration:true,baseDuration:30,description:"Lockpicking is <mag>% easier for <dur> seconds.",baseGold:0.5}
,"Fortify Magicka":{isPotion:true,fixedMagnitude:false,baseMagnitude:4,fixedDuration:true,baseDuration:60,description:"Magicka is increased by <mag> points for <dur> seconds.",baseGold:0.3}
,"Fortify Marksman":{isPotion:true,fixedMagnitude:false,baseMagnitude:4,fixedDuration:true,baseDuration:60,description:"Bows do <mag>% more damage for <dur> seconds.",baseGold:0.5}
,"Fortify One-handed":{isPotion:true,fixedMagnitude:false,baseMagnitude:4,fixedDuration:true,baseDuration:60,description:"One-handed weapons do <mag>% more damage for <dur> seconds.",baseGold:0.5}
,"Fortify Pickpocket":{isPotion:true,fixedMagnitude:false,baseMagnitude:4,fixedDuration:true,baseDuration:60,description:"Pickpocketing is <mag>% easier for <dur> seconds.",baseGold:0.5}
,"Fortify Restoration":{isPotion:true,fixedMagnitude:false,baseMagnitude:4,fixedDuration:true,baseDuration:60,description:"Restoration spells are <mag>% stronger for <dur> seconds.",baseGold:0.5}
,"Fortify Smithing":{isPotion:true,fixedMagnitude:false,baseMagnitude:4,fixedDuration:true,baseDuration:30,description:"For <dur> seconds, weapon and armor improving is <mag>% better.",baseGold:0.75}
,"Fortify Sneak":{isPotion:true,fixedMagnitude:false,baseMagnitude:4,fixedDuration:true,baseDuration:60,description:"You are <mag>% harder to detect for <dur> seconds.",baseGold:0.5}
,"Fortify Stamina":{isPotion:true,fixedMagnitude:false,baseMagnitude:4,fixedDuration:true,baseDuration:60,description:"Stamina is increased by <mag> points for <dur> seconds.",baseGold:0.3}
,"Fortify Two-handed":{isPotion:true,fixedMagnitude:false,baseMagnitude:4,fixedDuration:true,baseDuration:60,description:"Two-handed weapons do <mag>% more damage for <dur> seconds.",baseGold:0.5}
,"Frenzy":{isPotion:false,fixedMagnitude:false,baseMagnitude:1,fixedDuration:true,baseDuration:10,description:"Creatures and people up to level <mag> will attack anything nearby for <dur> seconds.",baseGold:15}
,"Invisibility":{isPotion:true,fixedMagnitude:true,baseMagnitude:0,fixedDuration:false,baseDuration:4,description:"Invisibility for <dur> seconds.",baseGold:100}
,"Lingering Damage Health":{isPotion:false,fixedMagnitude:false,baseMagnitude:1,fixedDuration:true,baseDuration:10,description:"Causes <mag> points of poison damage for <dur> seconds.",baseGold:12}
,"Lingering Damage Magicka":{isPotion:false,fixedMagnitude:false,baseMagnitude:1,fixedDuration:true,baseDuration:10,description:"Drains the target's Magicka by <mag> points per second for <dur> seconds.",baseGold:10}
,"Lingering Damage Stamina":{isPotion:false,fixedMagnitude:false,baseMagnitude:1,fixedDuration:true,baseDuration:10,description:"Drain the target's Stamina by <mag> points per second for <dur> seconds.",baseGold:1.8}
,"Paralysis":{isPotion:false,fixedMagnitude:true,baseMagnitude:0,fixedDuration:false,baseDuration:1,description:"Target is paralyzed for <dur> seconds.",baseGold:500}
,"Ravage Health":{isPotion:false,fixedMagnitude:false,baseMagnitude:2,fixedDuration:true,baseDuration:10,description:"Causes <mag> points of concentrated poison damage.",baseGold:0.4}
,"Ravage Magicka":{isPotion:false,fixedMagnitude:false,baseMagnitude:2,fixedDuration:true,baseDuration:10,description:"Concentrated poison damages magicka by <mag> points.",baseGold:1.0}
,"Ravage Stamina":{isPotion:false,fixedMagnitude:false,baseMagnitude:2,fixedDuration:true,baseDuration:10,description:"Concentrated poison damages stamina by <mag> points.",baseGold:1.6}
,"Regenerate Health":{isPotion:true,fixedMagnitude:false,baseMagnitude:5,fixedDuration:true,baseDuration:300,description:"Health regenerates <mag>% faster for <dur> seconds.",baseGold:0.1}
,"Regenerate Magicka":{isPotion:true,fixedMagnitude:false,baseMagnitude:5,fixedDuration:true,baseDuration:300,description:"Magicka regenerates <mag>% faster for <dur> seconds.",baseGold:0.1}
,"Regenerate Stamina":{isPotion:true,fixedMagnitude:false,baseMagnitude:5,fixedDuration:true,baseDuration:300,description:"Stamina regenerates <mag>% faster for <dur> seconds.",baseGold:0.1}
,"Resist Fire":{isPotion:true,fixedMagnitude:false,baseMagnitude:3,fixedDuration:true,baseDuration:60,description:"Resist <mag>% of fire damage for <dur> seconds.",baseGold:0.5}
,"Resist Frost":{isPotion:true,fixedMagnitude:false,baseMagnitude:3,fixedDuration:true,baseDuration:60,description:"Resist <mag>% of frost damage for <dur> seconds.",baseGold:0.5}
,"Resist Magic":{isPotion:true,fixedMagnitude:false,baseMagnitude:1,fixedDuration:true,baseDuration:60,description:"Resist <mag>% of magic for <dur> seconds.",baseGold:1}
,"Resist Poison":{isPotion:true,fixedMagnitude:false,baseMagnitude:4,fixedDuration:true,baseDuration:60,description:"Resist <mag>% of poison for <dur> seconds.",baseGold:0.5}
,"Resist Shock":{isPotion:true,fixedMagnitude:false,baseMagnitude:3,fixedDuration:true,baseDuration:60,description:"Resist <mag>% of shock damage for <dur> seconds.",baseGold:0.5}
,"Restore Health":{isPotion:true,fixedMagnitude:false,baseMagnitude:5,fixedDuration:true,baseDuration:0,description:"Restore <mag> points of Health.",baseGold:0.5}
,"Restore Magicka":{isPotion:true,fixedMagnitude:false,baseMagnitude:5,fixedDuration:true,baseDuration:0,description:"Restore <mag> points of Magicka.",baseGold:0.6}
,"Restore Stamina":{isPotion:true,fixedMagnitude:false,baseMagnitude:5,fixedDuration:true,baseDuration:0,description:"Restore <mag> Stamina.",baseGold:0.6}
,"Slow":{isPotion:false,fixedMagnitude:true,baseMagnitude:50,fixedDuration:false,baseDuration:5,description:"Target moves at 50% speed for <dur> seconds.",baseGold:1}
,"Waterbreathing":{isPotion:true,fixedMagnitude:true,baseMagnitude:0,fixedDuration:false,baseDuration:5,description:"Can breathe underwater for <dur> seconds.",baseGold:30}
,"Weakness to Fire":{isPotion:false,fixedMagnitude:false,baseMagnitude:3,fixedDuration:true,baseDuration:30,description:"Target is <mag>% weaker to fire damage for <dur> seconds.",baseGold:0.6}
,"Weakness to Frost":{isPotion:false,fixedMagnitude:false,baseMagnitude:3,fixedDuration:true,baseDuration:30,description:"Target is <mag>% weaker to frost damage for <dur> seconds.",baseGold:0.5}
,"Weakness to Magic":{isPotion:false,fixedMagnitude:false,baseMagnitude:2,fixedDuration:true,baseDuration:30,description:"Target is <mag>% weaker to magic for <dur> seconds.",baseGold:1}
,"Weakness to Poison":{isPotion:false,fixedMagnitude:false,baseMagnitude:2,fixedDuration:true,baseDuration:30,description:"Target is <mag>% weaker to poison for <dur> seconds.",baseGold:1}
,"Weakness to Shock":{isPotion:false,fixedMagnitude:false,baseMagnitude:3,fixedDuration:true,baseDuration:30,description:"Target is <mag>% weaker to shock damage for <dur> seconds.",baseGold:0.7}
};